/* swagger definition and configuration */
module.exports = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            "title": 'Backend API',
            "version": '1.0.0',
            "description": 'Backend API with autogenerated swagger documentation for calling each API with their response.',
        },
        schemes: [
            "http",
            "https"
        ],
        securityDefinitions: {
            BearerAuth: {
                type: "apiKey",
                description: "Type keyword 'Bearer' followed by a space and then enter your Token",
                in: "header",
                name: "Authorization"
            }
        },
        tags: [{
            name: "App",
            description: "Manage attributes and submit data",

        }]
    },
    // List of files(routes) to be processed.
    apis: ['./Routes/App.route.js',],
};